# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker

# add $SSHPASS variable with $DEPLOY_HOST password for sshpass command (or use export SSHPASS="your password")

variables:
  DEPLOY_HOST: "root@94.131.243.121:/home/lemp/lemp4docker-master/www/wellfuck.test/index.html"

image: ubuntu:latest

stages:
  - "build"
  - "test"
  - "deploy"

render_website:
  stage: build
  script:
    - apt update
    - apt install -y markdown
    - mkdir -p public
    - markdown website.md | tee public/index.html
  artifacts:
    paths:
      - "public/index.html"
  

test_website:
  stage: test
  script:
    - apt update
    - apt install -y libxml2-utils
    - xmllint --html public/index.html
  dependencies:
    - "render_website"

deploy_website_test:
  environment: test
  stage: deploy
  script:
    - apt update
    - apt install -y sshpass
    - echo -e " \nThis is test version" >> ./public/index.html
    - sshpass -e scp -P 22987 -oStrictHostKeyChecking=no ./public/index.html $DEPLOY_HOST
  dependencies:
    - "render_website"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy_website_prod:
  environment: prod
  stage: deploy
  script:
    - apt update
    - apt install -y sshpass
    - echo -e " \nThis is prod version" >> ./public/index.html
    - sshpass -e scp -P 22987 -oStrictHostKeyChecking=no ./public/index.html $DEPLOY_HOST
  dependencies:
    - "render_website"
  rules:
    - if: $CI_COMMIT_TAG
      when: manual 
