---
 - name: Install Apache and Upload page
   hosts: local_servers
   become: yes

   vars:
     source_file: ./index.html
     destin_file: /var/www/html

   tasks:
   - name: Install Apache
     apt: name=apache2 state=latest

   - name: Copy page to servers
     copy: src={{ source_file }} dest={{ destin_file }} mode=0555
     notify: Restart Apache

   - name: Start Web server
     service: name=apache2 state=started enabled=yes

   handlers:
   - name: Restart Apache
     service: name=apache2 state=restarted
