---
- name: Test Playbook
  hosts: local_servers
  become: yes

  vars:
    message1: Privet
    message2: Mir
    secret: hfrhgerggjgnnbrtnb
    mytext: "Privet"

  tasks:
  - name: Print secret
    debug:
      var: secret

  - debug:
      msg: "Secret: {{ secret }}"

  - debug:
      msg: "Owner of this server is {{ ansible_user }}"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ ansible_user }}"

  - debug:
      var: full_message

  - debug:
      var: ansible_os_family

  - shell: uptime
    register: results

  - debug:
      var: results.stdout

  - name: Say Hello
    debug: msg="Hello {{ item }}"
    loop:
      - "Alex"
      - "Michael"

  - name: Loop until example
    shell: echo -n X >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("XXXX") == false

  - name: Print output
    debug:
      var: output.stdout

  - name: Create folders
    include: create_folders.yml

  - name: Create files
    include: create_files.yml  mytext="Hello"

#  - name: Install packages
#    apt: name={{ item }} state=installed
#    loop:
#      - python
#      - tree
#      - nginx
