---
 - name: Install Apache and Upload page
   hosts: remote_servers
   become: yes

   vars:
     source_file: ./index.html
     destin_file: /var/www/html

   tasks:
   - name: Check and Print Linux
     debug: var=ansible_os_family

   - block:  # block for Ubuntu

       - name: Install Apache for Ubuntu
         apt: name=apache2 state=latest

       - name: Copy page to servers
         copy: src={{ source_file }} dest={{ destin_file }} mode=0555
         notify: Restart Apache Ubuntu

       - name: Start Web server
         service: name=apache2 state=started enabled=yes

     when: ansible_os_family == "Debian"

   - block:  # block for RedHat

       - name: Install Apache for RedHat
         yum: name=httpd state= latest

       - name: Copy page to servers
         copy: src={{ source_file }} dest={{ destin_file }} mode=0555
         notify: Restart Apache RedHat

       - name: Start Web server
         service: name=httpd state=started enabled=yes

     when: ansible_os_family == "RedHat"

   handlers:
   - name: Restart Apache Ubuntu
     service: name=apache2 state=restarted

   - name: Restart Apache RedHat
     service: name=httpd state=restarted
